### ISSUE TITLE
[Feat] 추천 질문 및 자산 프롬프트 엔지니어링

### ISSUE THREAD

**Issue by shinyeji-spea** [AegisLenz/AegisLenz-PE#27]
## 🔥 Issue
추천 질문 생성기 및 자산 프롬프트 엔지니어링

## ✅ TODO
- [ ] MITRE ATT&CK 자료 넣고 테스트
- [ ] 추천 질문 history에 넣는 값 고민
- [ ] 지속적인 프롬프트 엔지니어링
- [ ] 자산 쿼리 조회 오류 해결
- [ ] 자산에 스키마 주고 테스트
